/** The shape of public/data/countries.json. Generated by scripts/build-countries.mjs. */
export interface Country {
  /** ISO 3166-1 alpha-3, except Kosovo which uses Natural Earth's KOS. */
  iso: string;
  iso2: string | null;
  name: string;
  official: string;
  /** null only for the five rendered-only entities, which are never quizzed. */
  capital: string | null;
  /** Also marked correct — alternate or contested capitals. See docs/entity-decisions.md. */
  capitalAccept: string[];
  continent: string;
  subregion: string;
  lat: number | null;
  lon: number | null;
  pop: number;
  /** Prominence band 0 (most populous) to 4. Distractors stay within one band of the
   *  target, so an obscure country is never solvable by elimination. */
  salience: number;
  quizzable: boolean;
  /** False for the 29 countries too small to render at 110m; they get a dot marker. */
  hasPolygon: boolean;
  borders: string[];
  aliases: string[];
  /** A capital people confidently and wrongly give for this country, e.g. TUR -> Istanbul. */
  misconception: string | null;
  /** Present only on rendered-only entities: why it is not quizzed. */
  note?: string;
}

export type Skill = 'capital' | 'flag' | 'flagReverse' | 'map';
export const SKILLS: readonly Skill[] = ['capital', 'flag', 'flagReverse', 'map'] as const;

export const CONTINENTS = ['Europe', 'Africa', 'Asia', 'Americas', 'Oceania'] as const;
export type Continent = (typeof CONTINENTS)[number];

export interface AdjacencyEntry {
  /** Countries sharing a land border. */
  land: string[];
  /** [iso, km] maritime neighbours, nearest first. */
  near: [string, number][];
  /** [lon, lat] pole of inaccessibility of the largest landmass — guaranteed inside. */
  labelPoint: [number, number];
}
export type Adjacency = Record<string, AdjacencyEntry>;

